services:
  server-control-suite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-control-suite
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    command: server_control_bot.py
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "-q", "[p]ython.*server_control_bot"]
      interval: 30s
      timeout: 10s
      retries: 3