name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install additional dependencies if they exist
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt || echo "Some dependencies could not be installed"
        fi
    - name: Analysing the code with pylint
      run: |
        echo "Running pylint for code quality analysis (Python ${{ matrix.python-version }})"
        # Generate a nice output but don't fail the workflow
        pylint --fail-under=8.0 $(git ls-files '*.py') || echo "Your code has been rated at $(pylint --score=y $(git ls-files '*.py') 2>&1 | grep -oP 'Your code has been rated at \K[0-9.]+/10') - issues were found but workflow will continue"
