name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Make setup script executable
      run: chmod +x setup_ci.sh
    - name: Install dependencies
      run: |
        ./setup_ci.sh
    - name: Analysing the code with pylint
      run: |
        echo "Running pylint for code quality analysis (Python ${{ matrix.python-version }})"
        # Generate a nice output but don't fail the workflow
        pylint --rcfile=.pylintrc --fail-under=8.0 $(git ls-files '*.py') || echo "Pylint found issues but continuing workflow"
    - name: Debug Information
      run: |
        echo "Checking Python version: ${{ matrix.python-version }}"
        echo "Workspace directory contents:"
        ls -la
