name: Python Basic Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot==13.7
        pip install flake8
    - name: Check for syntax errors
      run: |
        # Stop the build if there are Python syntax errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Basic import check
      run: |
        # Try to import the module to catch import errors
        python -c "import server_control_bot" || echo "Import check failed but continuing" 