name: Python Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Make setup script executable
      run: chmod +x setup_ci.sh
    - name: Install dependencies
      run: |
        # Run the setup script
        ./setup_ci.sh
    - name: Analysing the code with pylint
      run: |
        # Use the project's pylint configuration with a non-zero exit code option
        echo "Running pylint with custom config"
        pylint --rcfile=.pylintrc $(git ls-files '*.py') || exit 0 